# Generated by Django 5.0.4 on 2024-04-11 12:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='todo_images/default.png', null=True, upload_to='todo_images/', verbose_name='Image')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'Title must be greater than 5 charapters')], verbose_name='Title')),
                ('text', models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(20, 'Body must be greater than 20 charapters')], verbose_name='Body')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('datecompleted', models.DateTimeField(blank=True, null=True, verbose_name='Completed')),
                ('important', models.CharField(choices=[('L', 'low'), ('M', 'medium'), ('H', 'high')], default='L', max_length=1, verbose_name='Priority')),
                ('status', models.CharField(choices=[('C', 'created'), ('I', 'in progress'), ('D', 'done')], default='C', max_length=1, verbose_name='Status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('perform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perform', to=settings.AUTH_USER_MODEL, verbose_name='Perform')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-important'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.todo', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_date'],
            },
        ),
    ]
